### ISSUE TITLE
Anisotropy implementation

### ISSUE THREAD

**Issue by wangyf** [plang85/rough_surfaces#6]
Hi,
I wonder how you implemented anisotropy roughness as you showed in the front page. I only find data you generate in doc folder. I appreciate in advance for your help.

Yongfei

**Comment by plang85** [comment]
yes, my bad - used a previous implementation for these plots. I'll try to port this soon

**Comment by plang85** [comment]
Done in #7 (take a look at examples/example_generate.py)
